@startuml
'https://plantuml.com/sequence-diagram

class ArrayAggregate
{
- int[] array
    + int getItem(int i)
    + int count()
}

interface Iterable
interface Iterator
Iterable <|.. ArrayAggregate
Iterator<|.. ArrayIterator
ArrayIterator --> ArrayAggregate: array

@enduml